# Generated by Django 3.2.9 on 2021-11-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='firstN',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastN',
            field=models.CharField(default='', max_length=30),
        ),
    ]
