# Generated by Django 3.2.9 on 2021-11-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20211106_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usermodels',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
